### PR TITLE
RoadmapGPT

### PR DESCRIPTION
**Pull request by mrna0**
Before merging, I guess you need to create a new branch.

### CODE REVIEW

**Comment by whoiskatrin** [comment]
@mrna0 could you please fix a merge conflict

**Comment by mrna0** [comment]
@whoiskatrin I did it.

**Comment by whoiskatrin** [comment]
@mrna0 build is failing, check  Error: Missing "key" prop for element in iterator  react/jsx-key

**Comment by whoiskatrin** [comment]
Hey, it doesn't seem like it's a good integration right now. Do you want to refine it to make it work with existing product and reopen PR later?

**Pull request closed without merging**
